import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "الفطرة",
  description: "Generated by create next app",
};

const cairo = localFont({
  src: [
    {
      path: "./fonts/Cairo-Regular.ttf",
      weight: "normal",
      style: "normal",
    },
  ],
  variable: "--font-cairo",
});

const monadi = localFont({
  src: [
    {
      path: "./fonts/ArbFONTS-Monadi.ttf",
      weight: "normal",
      style: "normal",
    },
  ],
  variable: "--font-monadi",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} ${monadi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
